[backup]
block_size = 4096
checksum = "sha256"
strategy = "timestamp"


[database]
driver = "sqlite"
path = "biscuit.db"

[key]
path = "key"

[log]
path = "biscuit.log"

[log.levels]
core = "info"
database = "info"
ssh = "info"
